import Router from "./router";
export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function dashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-5">
          <div className="col-span-1">
            <Router />
          </div>

          <div className="col-span-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
